/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoubtsRouteImport } from './routes/doubts'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAssessmentsRouteImport } from './routes/admin.assessments'
import { Route as AdminCodingRouteImport } from './routes/admin.coding'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnTrackRouteImport } from './routes/learn.$track'
import { Route as MockIndexRouteImport } from './routes/mock.index'
import { Route as MockTestIdRouteImport } from './routes/mock.$testId'
import { Route as MockTestIdAnalyticsRouteImport } from './routes/mock.$testId.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtsRoute = DoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodingRoute = AdminCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnTrackRoute = LearnTrackRouteImport.update({
  id: '/$track',
  path: '/$track',
  getParentRoute: () => LearnRoute,
} as any)
const MockIndexRoute = MockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestIdRoute = MockTestIdRouteImport.update({
  id: '/mock/$testId',
  path: '/mock/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestIdAnalyticsRoute = MockTestIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MockTestIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coding': typeof CodingRoute
  '/dashboard': typeof DashboardRoute
  '/doubts': typeof DoubtsRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/coding': typeof AdminCodingRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/learn/$track': typeof LearnTrackRoute
  '/mock/$testId': typeof MockTestIdRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/mock/': typeof MockIndexRoute
  '/mock/$testId/analytics': typeof MockTestIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coding': typeof CodingRoute
  '/dashboard': typeof DashboardRoute
  '/doubts': typeof DoubtsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/coding': typeof AdminCodingRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/learn/$track': typeof LearnTrackRoute
  '/mock/$testId': typeof MockTestIdRouteWithChildren
  '/learn': typeof LearnIndexRoute
  '/mock': typeof MockIndexRoute
  '/mock/$testId/analytics': typeof MockTestIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coding': typeof CodingRoute
  '/dashboard': typeof DashboardRoute
  '/doubts': typeof DoubtsRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/coding': typeof AdminCodingRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/learn/$track': typeof LearnTrackRoute
  '/mock/$testId': typeof MockTestIdRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/mock/': typeof MockIndexRoute
  '/mock/$testId/analytics': typeof MockTestIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/coding'
    | '/dashboard'
    | '/doubts'
    | '/learn'
    | '/login'
    | '/me'
    | '/notifications'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/coding'
    | '/admin/content'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/users'
    | '/learn/$track'
    | '/mock/$testId'
    | '/learn/'
    | '/mock/'
    | '/mock/$testId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/coding'
    | '/dashboard'
    | '/doubts'
    | '/login'
    | '/me'
    | '/notifications'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/coding'
    | '/admin/content'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/users'
    | '/learn/$track'
    | '/mock/$testId'
    | '/learn'
    | '/mock'
    | '/mock/$testId/analytics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/coding'
    | '/dashboard'
    | '/doubts'
    | '/learn'
    | '/login'
    | '/me'
    | '/notifications'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/coding'
    | '/admin/content'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/users'
    | '/learn/$track'
    | '/mock/$testId'
    | '/learn/'
    | '/mock/'
    | '/mock/$testId/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CodingRoute: typeof CodingRoute
  DashboardRoute: typeof DashboardRoute
  DoubtsRoute: typeof DoubtsRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  MockTestIdRoute: typeof MockTestIdRouteWithChildren
  MockIndexRoute: typeof MockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubts': {
      id: '/doubts'
      path: '/doubts'
      fullPath: '/doubts'
      preLoaderRoute: typeof DoubtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coding': {
      id: '/admin/coding'
      path: '/coding'
      fullPath: '/admin/coding'
      preLoaderRoute: typeof AdminCodingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$track': {
      id: '/learn/$track'
      path: '/$track'
      fullPath: '/learn/$track'
      preLoaderRoute: typeof LearnTrackRouteImport
      parentRoute: typeof LearnRoute
    }
    '/mock/': {
      id: '/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof MockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$testId': {
      id: '/mock/$testId'
      path: '/mock/$testId'
      fullPath: '/mock/$testId'
      preLoaderRoute: typeof MockTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$testId/analytics': {
      id: '/mock/$testId/analytics'
      path: '/analytics'
      fullPath: '/mock/$testId/analytics'
      preLoaderRoute: typeof MockTestIdAnalyticsRouteImport
      parentRoute: typeof MockTestIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminCodingRoute: typeof AdminCodingRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminCodingRoute: AdminCodingRoute,
  AdminContentRoute: AdminContentRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LearnRouteChildren {
  LearnTrackRoute: typeof LearnTrackRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnTrackRoute: LearnTrackRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface MockTestIdRouteChildren {
  MockTestIdAnalyticsRoute: typeof MockTestIdAnalyticsRoute
}

const MockTestIdRouteChildren: MockTestIdRouteChildren = {
  MockTestIdAnalyticsRoute: MockTestIdAnalyticsRoute,
}

const MockTestIdRouteWithChildren = MockTestIdRoute._addFileChildren(
  MockTestIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CodingRoute: CodingRoute,
  DashboardRoute: DashboardRoute,
  DoubtsRoute: DoubtsRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  MockTestIdRoute: MockTestIdRouteWithChildren,
  MockIndexRoute: MockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
